# Generated by Django 3.2.8 on 2021-10-25 21:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20211025_0115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Articles',
        ),
    ]
