# Generated by Django 3.2.8 on 2021-10-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='post_dislike',
            field=models.IntegerField(default=0, verbose_name='Дизлайк'),
        ),
        migrations.AddField(
            model_name='articles',
            name='post_like',
            field=models.IntegerField(default=0, verbose_name='Лайк'),
        ),
    ]
