# Generated by Django 3.2.8 on 2021-10-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='total',
            field=models.IntegerField(default=0, verbose_name='Всего голосов'),
        ),
    ]
